# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Department.create(name: "Women's")
Department.create(name: "Men's")
Department.create(name: "Accessories")

Category.create(name:"Shirts", department_id: 1)
Category.create(name:"Pants", department_id: 1)
Category.create(name:"Dresses", department_id: 1)
Category.create(name:"Sweaters", department_id: 1)
Category.create(name:"Jackets", department_id: 1)
Category.create(name:"Shoes", department_id: 1)
Category.create(name:"Shirts", department_id: 2)
Category.create(name:"Pants", department_id: 2)
Category.create(name:"Sweaters", department_id: 2)
Category.create(name:"Jackets", department_id: 2)
Category.create(name:"Shoes", department_id: 2)
Category.create(name:"Bags", department_id: 3)
Category.create(name:"Jewelry", department_id: 3)

Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 1, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 2, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 3, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 4, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 5, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 6, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 7, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 8, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 9, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 10, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 11, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 12, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
Item.create(description:"x", price: 10, category_id: 13, name: "name", image: "image", size: "small")
